---
pipeline:
  projectIdentifier: "nv_project"
  orgIdentifier: "default"
  tags: {}
  stages:
  - stage:
      name: "c1"
      identifier: "c1"
      description: ""
      type: "Custom"
      spec:
        execution:
          steps:
          - step:
              type: "ShellScript"
              name: "Shell Script_1"
              identifier: "ShellScript_1"
              spec:
                shell: "Bash"
                onDelegate: true
                source:
                  type: "Inline"
                  spec:
                    script: "exit 1"
                environmentVariables: []
                outputVariables: []
              timeout: "10m"
          - step:
              type: "HarnessApproval"
              name: "Harness Approval_1"
              identifier: "HarnessApproval_1"
              spec:
                approvalMessage: "Please review the following information and approve\
                  \ the pipeline progression"
                includePipelineExecutionHistory: true
                approvers:
                  userGroups:
                  - "account._account_all_users"
                  minimumCount: 1
                  disallowPipelineExecutor: false
                approverInputs: []
              timeout: "1d"
  identifier: "Archit_Waitapproval_remote_pipeline"
  name: "Archit Wait-approval remote pipeline"
